---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
  - name: boot-twitter-sentiment-src

run:
  path: mvn
  args: ["-f", "boot-twitter-sentiment-src/pom.xml", "test"]

params:
  TERM: -dumb
